"""Add invite fields to users

Revision ID: bfaf61e5e1a7
Revises: c2b52a79faab
Create Date: 2026-05-14 17:34:04.867207
"""
from alembic import op
import sqlalchemy as sa


revision = 'bfaf61e5e1a7'
down_revision = 'c2b52a79faab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_link', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('invite_expire_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'invite_expire_at')
    op.drop_column('users', 'invite_link')
    # ### end Alembic commands ###
