"""Add tables creation

Revision ID: c2b52a79faab
Revises: c8eed96d4900
Create Date: 2026-05-13 19:26:39.664354
"""
from alembic import op
import sqlalchemy as sa


revision = 'c2b52a79faab'
down_revision = 'c8eed96d4900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
