"""Create tables with enum

Revision ID: c8eed96d4900
Revises: 521fd38f0bb8
Create Date: 2026-05-13 13:17:11.908694
"""
from alembic import op
import sqlalchemy as sa


revision = 'c8eed96d4900'
down_revision = '521fd38f0bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
